spring:
  application:
    name: seedlist #应用名称
  datasource:
    # 配置数据库
    url: jdbc:mysql://localhost:3306/seedlist?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
#    url: jdbc:mysql://101.34.244.190:3306/seedlist?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: '[m5i=00s3TYW'
#    password: 123456root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000 #客户端等待连接池连接的最大毫秒数
      minimum-idle: 4 #连接池中维护的最小空闲连接数
      maximum-pool-size: 8  #最大池大小
      idle-timeout: 30000   #允许连接池在连接池中空闲的最长时间（毫秒）
      max-lifetime: 45000 #池中连接关闭的最长生命周期（毫秒）
      auto-commit: true #从池返回的连接的默认自动提交行为（默认为true）
      pool-name: SpringDataJPAHikariCP #连接池的名称
  jpa:
    show-sql: true
    hibernate:
      #DDL:用于定义数据库的三层结构，包括外模式、概念模式、内模式及其相互之间的映像，定义数据的完整性，安全控制等约束
      ddl-auto: none #?????
      #?????
      #create:  每次运行应用程序时，都会重新创建表，所以，数据都会丢失
      #create-drop:每次运行程序时会创建表结构，然后程序结束时清空数据
      #update: 每次运行程序没有表时会创建表，如果对象改变会更新表结构，原有数据不会清除，只会更新
      #validate: 运行程序会校验数据与数据库的字段类型是否相同，字段不同会报错
    # 关闭懒加载配置，否则会报错
    open-in-view: false
    properties:
      hibernate:
        #打印执行的sql及参数
        show_sql: true
        #格式化输出的sql，否则会一行显示
        #format_sql: true
jwt:
  config:
    key: root
    failureTime: 3600000

server:
  port: 8008 # 服务器端口
  servlet:
    context-path: /api
logging:
  config: classpath:logging-config.xml